image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

fullnameOverride: "helloworld"

container:
  port: 8080

config:
  test: "hello"

resources: 
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 125m
    memory: 250Mi

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

virtualservice:
  namespace: ns-sync-hdfc-demo

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95